### ISSUE TITLE
Implement Google login authentication

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/sanchay-ai-frontend#1]
- Implement Google authentication in the Login component of the project.
- Location: src/Components/Login.js
- User should be able to access the / and the /projects routes only if authenticated.
- Store the auth token in localStorage since redux is not setup yet.

**Comment by mohit9222** [comment]
Hi Aadesh,
I will look into this issue.

**Comment by localhostd3veloper** [comment]
@aadeshkulkarni Is it done?

**Comment by aadeshkulkarni** [comment]
> @aadeshkulkarni Is it done?

Yes, this is now fixed.
