### ISSUE TITLE
[Improvement] Checkbox isn't selected when clicked on Label  

### ISSUE THREAD

**Issue by theprogrammerinyou** [aadeshkulkarni/sanchay-ai-frontend#3]
When the user clicks on transcription or subtitles or thumbnail label on the landing page the checkbox isn't selected which is not a good UX. 

The user should be able to select checkbox when user clicks on label.
<img width="1512" alt="Screenshot 2023-12-31 at 12 45 04" src="https://github.com/aadeshkulkarni/sanchay-ai-frontend/assets/29782911/98c5ef7e-29d5-4634-9fd0-11fdbe231dc2">

**Comment by aadeshkulkarni** [comment]
Sounds good. Can you pick this up ?

**Comment by theprogrammerinyou** [comment]
Sure
